version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: nubbin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
