version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: nubbin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../02-backend
    environment:
      PORT: 4000
      JWT_SECRET: supersecretchange
      DATABASE_URL: postgres://postgres:postgres@db:5432/nubbin
      CORS_ORIGIN: http://localhost
    depends_on:
      - db
    ports:
      - "4000:4000"

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - backend
    ports:
      - "8080:80"
    volumes:
      - ../01-frontend:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  db_data:
